### PR TITLE
Add an alt manager

### PR DESCRIPTION
**Pull request by NepNep21**
**Describe the pull**
It will, when ready, add an alt manager GUI to lambda

**Describe how this pull is helpful**
Many people like alt managers, and it can be useful for dev environments

**Additional context**
This is *not* ready to be merged, it is very untested and in the ways it was tested it does not work yet, i am releasing this draft PR to request assistance to figure out the bugs, first of all the  "Cancel" button never appearing
Another thing that should be changed before merging is the oauth client id to an official lambda one

### CODE REVIEW

**Comment by NepNep21** [comment]
This mostly works now, just waiting for constructor to fix his azure app

**Comment by Doogie13** [comment]
will this ever be merged?

**Comment by NepNep21** [comment]
Iirc it works now (minus the merge conflict I'll fix in a bit), but constructor wanted it to be done with the lambda GUI system and I haven't been able to implement that well, it's up to him, or anyone who may want to help.

**Comment by Doogie13** [comment]
fair

**Comment by P529** [comment]
Damn, great work!

Yeah idk why the maintainer of this repo doesnt merge it. Ive tested it and it works pretty good! 

Maybe show the error messages in the gui as well and then its perfect. Also looking pretty fly!

**Pull request closed without merging**
