### PR TITLE
Remove FakeVanillaClient

### PR DESCRIPTION
**Pull request by NepNep21**
**Describe the pull**
Remove the FakeVanillaClient module and the mixin it uses

**Describe how this pull is helpful**
FakeVanillaClient is useless for anarchy

### CODE REVIEW

**Comment by smokeytube** [comment]
what would be the benefit of removing it?

**Comment by NepNep21** [comment]
> what would be the benefit of removing it?

People then couldn't make the argument that lambda has non anarchy modules

**Comment by smokeytube** [comment]
who cares if it has non-anarchy modules?

**Comment by scorbett123** [comment]
> who cares if it has non-anarchy modules?

It goes against what many of the devs believe that the client should be used for, on the discord you can be banned for using lambda for non anarchy purposes. Having this module is basically endorsing that use.

**Comment by ToxicAven** [comment]
> who cares if it has non-anarchy modules?

some guy in the discord (luv u @IUDevman) was wisecracking about it, really not an issue lol

**Review by ToxicAven — APPROVED** [review]

**Review by scorbett123 — APPROVED** [review]

**Comment by smokeytube** [comment]
> > who cares if it has non-anarchy modules?
> 
> some guy in the discord (luv u @IUDevman) was wisecracking about it, really not an issue lol

some kid made a joke? Shiver me fucking timbers

**Comment by IUDevman** [comment]
> > > who cares if it has non-anarchy modules?
> > 
> > 
> > some guy in the discord (luv u @IUDevman) was wisecracking about it, really not an issue lol
> 
> some kid made a joke? Shiver me fucking timbers

I'm just a king making sure god tier clients stay true to their purpose. 🙏 If you ever want to talk to me about the ethics behind uploading "discord token loggers written in the D programming language", feel free to HMU.

**Review by Xiaro — APPROVED** [review]

**Comment by smokeytube** [comment]
> > > > who cares if it has non-anarchy modules?
> > > 
> > > 
> > > some guy in the discord (luv u @IUDevman) was wisecracking about it, really not an issue lol
> > 
> > 
> > some kid made a joke? Shiver me fucking timbers
> 
> I'm just a king making sure god tier clients stay true to their purpose. 🙏 If you ever want to talk to me about the ethics behind uploading "discord token loggers written in the D programming language", feel free to HMU.

That repo makes malware public so microsoft or whoever can add signatures to their antiviruses. It's not unethical unless I use it against someone.

**Pull request merged**
