### PR TITLE
Add vanilla mode to efly, making optimized pitch corrections

### PR DESCRIPTION
**Pull request by NepNep21**
**Describe the pull**
Adds a mode to efly that automatically looks up and down for you

**Describe how this pull is helpful**
According to someone i asked this currently works on 2b2t with no lag, though more testing is recommended before merging

**Additional context**
Currently this works by modifying player.rotationPitch, which is not ideal  as it affects the player camera, it is probably possible to spoof it with packets but i have been unsuccessful when i tried, you can commit here if you get it working

### CODE REVIEW

**Comment by Avanatiker** [comment]
According to my tests it will just continue to look down when i activated a firework. Also i had bugs that the player was vertical instead of horizontal while flying. Also it would need packet movement and a freely moving cam.

**Comment by NepNep21** [comment]
1. I didn't think about that, I'll change it
2. Interesting, no idea why, I'll look into it
3. I already mentioned that, i tried it but couldn't figure it out, i figured you would be able to do it

**Comment by NepNep21** [comment]
This commit should make it look up when the player is boosted

**Comment by mmvanheusden** [comment]
Should not rotate instantly for better anticheat compatibility

**Comment by NepNep21** [comment]
The latest commit (by doogie) allows you to look freely while flying, i think this is ready to merge now? If you find any other issues please state them :)

**Comment by Doogie13** [comment]
https://youtu.be/vsb7fOucpKI forgot to send this here

Tested on 2b2t.dev

**Comment by Avanatiker** [comment]
I dont really like that you use quite a big chunk of minecraft code. Cant you just use mixins to archive this more clean? I cant merge this due to copyright infringement

**Comment by NepNep21** [comment]
I will look into it

**Comment by NepNep21** [comment]
Doogie tested it for rusher compatibility and i fixed a setting bug, i believe this is now ready to be merged

**Review by Avanatiker — APPROVED** [review]

**Comment by dekrom** [comment]
This release have compatibility problems with future client, at least in my build, ill try building again, anyone getting the same error?

**Comment by NepNep21** [comment]
> This release have compatibility problems with future client, at least in my build, ill try building again, anyone getting the same error?

Make an issue with logs, don't use PR comments for that

**Pull request merged**
