### PR TITLE
Allow lambda to load on systems where DiscordRPC is unavailable, using lazy initialization

### PR DESCRIPTION
**Pull request by NepNep21**
**Describe the pull**
Lazily initialize IPCClient

**Describe how this pull is helpful**
It's better to be able to play without DiscordRPC than not be able to play at all

**Additional context**
This is likely a temporary solution, i am currently working on a custom IPC implementation that should work on all platforms and will hopefully fix other issues with the current library

### CODE REVIEW

**Comment by NepNep21** [comment]
Merging seems to have borked something :woeis:, going to fix it

**Comment by NepNep21** [comment]
Hey @Avanatiker i just noticed that you removed ipc.close() in a previous commit, not having it causes the game to crash when the module is enabled again after being disabled, what was the reason for you removing it? I readded it for now

**Comment by Avanatiker** [comment]
It was causing errors in log on game shutdown

**Comment by NepNep21** [comment]
> It was causing errors in log on game shutdown

Well, since it's necessary for the module to work properly I'll mark this as ready, if you have suggestions before merging I'll look at them tomorrow

**Comment by Avanatiker** [comment]
Its still throwing that error. Cant we catch it somehow? you sure its supposed to do that?

[04:57:12] [Thread-9/INFO] [STDERR]: [com.jagrosh.discordipc.IPCClient:lambda$startReading$1:280]: java.net.SocketException: Not open
[04:57:12] [Thread-9/INFO] [STDERR]: [com.jagrosh.discordipc.IPCClient:lambda$startReading$1:280]: 	at org.newsclub.net.unix.AFUNIXSocketImpl.validFdOrException(AFUNIXSocketImpl.java:425)
[04:57:12] [Thread-9/INFO] [STDERR]: [com.jagrosh.discordipc.IPCClient:lambda$startReading$1:280]: 	at org.newsclub.net.unix.AFUNIXSocketImpl.access$200(AFUNIXSocketImpl.java:46)
[04:57:12] [Thread-9/INFO] [STDERR]: [com.jagrosh.discordipc.IPCClient:lambda$startReading$1:280]: 	at org.newsclub.net.unix.AFUNIXSocketImpl$AFUNIXInputStream.available(AFUNIXSocketImpl.java:362)
[04:57:12] [Thread-9/INFO] [STDERR]: [com.jagrosh.discordipc.IPCClient:lambda$startReading$1:280]: 	at com.jagrosh.discordipc.entities.pipe.UnixPipe.read(UnixPipe.java:47)
[04:57:12] [Thread-9/INFO] [STDERR]: [com.jagrosh.discordipc.IPCClient:lambda$startReading$1:280]: 	at com.jagrosh.discordipc.IPCClient.lambda$startReading$1(IPCClient.java:244)
[04:57:12] [Thread-9/INFO] [STDERR]: [com.jagrosh.discordipc.IPCClient:lambda$startReading$1:280]: 	at java.lang.Thread.run(Thread.java:748)
[04:57:12] [Client thread/WARN] [minecraft/SoundManager]: Author: Paul Lamb, www.paulscode.com
Process exited with code 0.

**Comment by Avanatiker** [comment]
Beside the error on shutdown (which may be fixed by removing the shutdown event listener) its still crashing for me when i close discord then disable the module.

**Comment by Avanatiker** [comment]
It should try to reconnect to discord until its back up without spamming console too

**Comment by NepNep21** [comment]
> Its still throwing that error. Cant we catch it somehow? you sure its supposed to do that?

It happens in the library's read thread, so i don't think we can catch it? It's definitely not supposed to do it though



> Beside the error on shutdown (which may be fixed by removing the shutdown event listener) its still crashing for me when i close discord then disable the module.

Ah, i'll look into that

**Comment by NepNep21** [comment]
Fixed what i could, also my plan to make a better IPC system from scratch is only possible with java 16+, so i'll have to wait for 1.18 before doing that, meaning this PR won't be as temporary as i thought

**Comment by Avanatiker** [comment]
OK shutdown error is gone. Only problem i found is if you close discord and then open again it wont automatically reconnect to the RPC i will merge it anyways. if you find a way connect it again please open a pull request

**Review by Avanatiker — APPROVED** [review]

**Comment by NepNep21** [comment]
> OK shutdown error is gone. Only problem i found is if you close discord and then open again it wont automatically reconnect to the RPC i will merge it anyways. if you find a way connect it again please open a pull request

I guess i forgot about that, my bad, shouldn't be too big of an issue to fix, i also need to fix the bug with it showing you're in the main menu or have no dimension in some cases, i'll fix both in a future PR

**Pull request merged**
