### PR TITLE
Finally fixes github actions building

### PR DESCRIPTION
**Pull request by NepNep21**
**Describe the pull**
Fixes github actions by immediately running the setup script before every build

**Describe how this pull is helpful**
Actions is important for people to get the latest commit without having to build themselves, and for testing features

**Additional context**
This really shouldn't work but somehow does

### CODE REVIEW

**Comment by IUDevman** [comment]
The real question is where is colored signs

**Comment by Avanatiker** [comment]
Weird ill look at this tomorrow but nice!

**Comment by ItCameFr0mMars** [comment]
finally ballin fix

**Comment by Avanatiker** [comment]
I used this info for a cleaner workaround thanks for it :)

**Pull request closed without merging**
