### PR TITLE
Add mixin support to plugins

### PR DESCRIPTION
**Pull request by NepNep21**
**Describe the pull**
Allow plugins to load mixins by early loading from coremodspace

**Describe how this pull is helpful**
It allows plugins to implement more advanced behavior

**Additional context**
There are a few things to note about this:
1. Currently, plugins using mixins MUST use the mixin config name format of "mixins.\<name of plugin as stated in the plugin info\>.json, it's possible to change this by adding an extra config option specifying the name of the mixin config"
2. Plugins using mixins MUST NOT interact with minecraft in any way from initial classloading, if that would be at all possible, they must wait until onLoad() is called
3. Right now, the hot reload config being false is assumed to always be a plugin using mixins, if you think that shouldn't be the case, i can change it and add another config option

### CODE REVIEW

**Comment by NepNep21** [comment]
As discussed on discord this should cause a version increase, i am currently waiting on confirmation about whether i should add it myself here or if someone should do it after merge

**Comment by Avanatiker** [comment]
I will do it on merge.

**Comment by Doogie13** [comment]
Coild there no be an option to half reload a plugin? (reload everything but mixins, which cannot be reloaded)

**Comment by NepNep21** [comment]
> Could there not be an option to half reload a plugin? (reload everything but mixins, which cannot be reloaded)

It's possible, but could break things and in general would probably lead to confused users do i don't think it's a good idea

**Comment by KMatias123** [comment]
> > Could there not be an option to half reload a plugin? (reload everything but mixins, which cannot be reloaded)
> 
> It's possible, but could break things and in general would probably lead to confused users so i don't think it's a good idea

It would make debugging plugins a lot faster though

**Review by Avanatiker — APPROVED** [review]

**Pull request merged**
